"""Initial migration with UUID

Revision ID: 5a225a9e0dd0
Revises: 
Create Date: 2025-12-03 00:49:32.337892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a225a9e0dd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users') # Skipped
    # op.drop_table('usage_logs') # Skipped
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat_messages', 'sender',
               existing_type=postgresql.ENUM('user', 'ai', name='sender_type'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('chat_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_constraint(op.f('chat_sessions_document_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_constraint(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'documents', ['document_id'], ['id'])
    op.alter_column('document_embeddings', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document_embeddings', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('document_embeddings_embedding_idx'), table_name='document_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    op.drop_constraint(op.f('document_embeddings_document_id_fkey'), 'document_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'document_embeddings', 'documents', ['document_id'], ['id'])
    op.drop_column('document_embeddings', 'page_number')
    op.drop_column('document_embeddings', 'embedding')
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('documents', 'file_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='doc_status'),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::doc_status"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    # op.drop_column('documents', 'visibility')
    # op.drop_column('documents', 'topic')
    # op.drop_column('documents', 'course_name')
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', postgresql.ENUM('processing', 'completed', 'failed', name='processing_status'), server_default=sa.text("'processing'::processing_status"), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('course_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('visibility', postgresql.ENUM('public', 'private', name='doc_visibility'), server_default=sa.text("'private'::doc_visibility"), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='doc_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::doc_status"))
    op.alter_column('documents', 'file_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('document_embeddings', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('document_embeddings', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('document_embeddings_document_id_fkey'), 'document_embeddings', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    op.create_index(op.f('document_embeddings_embedding_idx'), 'document_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('document_embeddings', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('document_embeddings', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_sessions_document_id_fkey'), 'chat_sessions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_messages', 'sender',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'ai', name='sender_type'),
               nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # op.create_table('usage_logs', ...) # Skipped
    # op.create_table('users', ...) # Skipped
    # ### end Alembic commands ###
